name: frosty_friday_challenges
version: 1.0.0
config-version: 2
profile: frosty_friday_challenges
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  frosty_friday_challenges:
    +materialized: view
